### ISSUE TITLE
About line 544 in src/models/EMPDG/model.py

### ISSUE THREAD

**Issue by 27182812** [Sahandfer/CEM#4]
Hello, excellent work!
About line 544 in src/models/EMPDG/model.py, the original line is "weights_best = state["models_g"]", I think maybe it should be "weights_best = state["model"]".

**Comment by Sahandfer** [comment]
Thank you for raising the issue, you are correct. I believe this is a bug if you want to load an EMPDG checkpoint for testing. However, note that it doesn't affect our evaluation and obtained results since we ran testing immediately after training so the weights for this model didn't need to be loaded. Regardless, I have fixed this issue and appreciate your feedback.

**Comment by 27182812** [comment]
Thank you for your reply! Yes, it will not affect the results. I revised it and ran it again. All Baseline results in the paper are reproducible. Great job!
